# Generated by Django 6.0.7 on 2026-07-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("location", models.CharField(max_length=255)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("price", models.BigIntegerField(db_index=True)),
                ("previous_price", models.BigIntegerField(blank=True, null=True)),
                ("current_price", models.BigIntegerField(blank=True, null=True)),
                ("bedrooms", models.PositiveIntegerField()),
                ("bathrooms", models.PositiveIntegerField()),
                ("sqft", models.PositiveIntegerField()),
                ("status", models.CharField(db_index=True, max_length=50)),
                ("featured", models.BooleanField(default=False)),
                ("luxury", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "building_approval",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("survey", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "document_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                ("parking", models.PositiveIntegerField(blank=True, null=True)),
                ("video_tour", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("is_visible", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_title", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("message", models.TextField(blank=True)),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Property Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_upload",
                    models.ImageField(
                        blank=True,
                        help_text="Original uploaded image",
                        null=True,
                        upload_to="property_images/original/",
                    ),
                ),
                (
                    "image_optimized",
                    models.ImageField(
                        blank=True,
                        help_text="Optimized web version of the image",
                        null=True,
                        upload_to="property_images/optimized/",
                    ),
                ),
                (
                    "image_thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail size image",
                        null=True,
                        upload_to="property_images/thumbnails/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Fallback URL for external images",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="core_proper_slug_8da4f0_idx"),
                    models.Index(
                        fields=["is_deleted"], name="core_proper_is_dele_f54683_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="core.propertytype",
            ),
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("description", models.CharField(max_length=500)),
                ("icon", models.CharField(max_length=50)),
                ("features", models.JSONField(blank=True, default=list)),
                ("long_description", models.TextField(blank=True, null=True)),
                ("process", models.JSONField(blank=True, default=list)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="core_servic_slug_4b9ad5_idx"),
                    models.Index(
                        fields=["is_deleted"], name="core_servic_is_dele_1c8757_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_title", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="core.servicetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Service Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("session_key__isnull", False)),
                        fields=("property", "session_key"),
                        name="unique_property_session_like",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("ip_address__isnull", False)),
                        fields=("property", "ip_address"),
                        name="unique_property_ip_like",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["slug"], name="core_proper_slug_b23ff2_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["city"], name="core_proper_city_d99175_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["status"], name="core_proper_status_95c99c_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["price"], name="core_proper_price_652b7d_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["is_visible"], name="core_proper_is_visi_aa9467_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["is_deleted"], name="core_proper_is_dele_0bf473_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["created_at"], name="core_proper_created_a942a9_idx"
            ),
        ),
    ]
