# Generated by Django 6.0.7 on 2026-07-13 21:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Responded', 'Responded'), ('Closed', 'Closed')], db_index=True, default='Pending', max_length=50)),
                ('replied', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mabel Homes', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('phone_primary', models.CharField(blank=True, max_length=50)),
                ('phone_secondary', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('footer_text', models.TextField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('property_enquiry', 'Property Enquiry'), ('service_enquiry', 'Service Enquiry'), ('contact', 'Contact Message'), ('like', 'Property Like'), ('system', 'System')], db_index=True, default='system', max_length=30),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='replied',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='serviceenquiry',
            name='replied',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='propertyenquiry',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='propertyenquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Responded', 'Responded'), ('Closed', 'Closed')], db_index=True, default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceenquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Responded', 'Responded'), ('Closed', 'Closed')], db_index=True, default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('reply', 'Reply'), ('upload', 'Upload'), ('settings', 'Settings Change'), ('other', 'Other')], db_index=True, max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email_delivered', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enquiry Reply',
                'verbose_name_plural': 'Enquiry Replies',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_library/')),
                ('file_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], db_index=True, max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('folder', models.CharField(blank=True, default='', help_text='Optional folder/category name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_upload', models.FileField(blank=True, help_text='Uploaded video file (MP4, WebM, MOV)', null=True, upload_to='property_videos/', validators=[core.models.validate_video_file])),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or other external video URL', max_length=1000, null=True)),
                ('video_type', models.CharField(choices=[('upload', 'Uploaded File'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('external', 'External URL')], db_index=True, default='upload', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
