# Generated by Django 6.0.7 on 2026-07-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage_responded_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propertylike',
            name='unique_property_ip_like',
        ),
    ]
