# Generated by Django 6.0.7 on 2026-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_propertylike_unique_property_ip_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='max_price',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
