# Generated by Django 6.0.7 on 2026-07-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_property_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], db_index=True, default='NGN', max_length=3),
        ),
    ]
