# Generated by Django 6.0.7 on 2026-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_currency_to_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('property', 'Property'), ('shortlet', 'Shortlet')], db_index=True, default='property', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='guests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='listing_type',
            field=models.CharField(choices=[('property', 'Property'), ('shortlet', 'Shortlet')], db_index=True, default='property', max_length=20),
        ),
    ]
